fix: [#266] add null checking and default value based on iOS since getCurrency can produce null
litecoin-foundation/litewallet-android pull request #278
Opened 2024-11-20 08:54 UTC by andhikayuana

# Overview
Previous implementation didn't have default value, for example if first time user want to do transaction then the local value didn't exists it will return null, [check this](https://github.com/litecoin-foundation/litewallet-android/blob/98bcc4a594610219a11dd3528991ea24fa6951a7/app/src/main/java/com/breadwallet/tools/sqlite/CurrencyDataSource.java#L91-L110).
add default value based on iOS [here](https://github.com/litecoin-foundation/litewallet-ios/blob/9ef6ba8f9cf8ef57f3c6056c31304c6197cafa7a/litewallet/Constants/Functions.swift#L44)

2024-11-20 17:46 UTC, josikie reviewed
Good point. But why the initial value 83.00? Is it Litecoin price? Can you give me the reason. Thank you @andhikayuana

2024-11-20 20:07 UTC, josikie approved these changes

2024-11-20 21:54 UTC, andhikayuana commented
> Good point. But why the initial value 83.00? Is it Litecoin price? Can you give me the reason. Thank you @andhikayuana

I just add the value based on iOS https://github.com/litecoin-foundation/litewallet-ios/blob/9ef6ba8f9cf8ef57f3c6056c31304c6197cafa7a/litewallet/Constants/Functions.swift#L44

2024-11-21 05:16 UTC, kcw-grunt commented
> Good point. But why the initial value 83.00? Is it Litecoin price? Can you give me the reason. Thank you @andhikayuana

You both asked a great question.  This was done `in the dark`  At the time, it was close to price  but no one really questioned it.  I have some ideas to do this better...look for a PR.

2024-11-21 06:05 UTC, kcw-grunt requested changes
LGTM...just a small removal.

2024-11-21 06:05 UTC, kcw-grunt commented on app/src/main/java/com/breadwallet/tools/util/Utils.java
> +        /**
Please remove lines 307-309.  Adding to the PR

2024-11-21 06:06 UTC, kcw-grunt commented
Adding your notes @andhikayuana  for historical reference
```
* current solution, add default rate based on iOS: https://github.com/litecoin-foundation/litewallet-ios/blob/9ef6ba8f9cf8ef57f3c6056c31304c6197cafa7a/litewallet/Constants/Functions.swift#L44
         * and add null checking after `CurrencyDataSource.getInstance(app).getCurrencyByIso(usIso);`
         */
```

2024-11-21 11:24 UTC, merged